create table DatabaseType (
    id number generated by default on null as identity,
    type varchar2(255) not null,
    triggerTemplate clob,
    constraintTemplate clob not null,
    constraint pk_database_type primary key (id)
);

create table Database (
    id number generated by default on null as identity,
    databaseType number not null,
    name varchar2(255) not null,
    username varchar2(255) not null,
    password varchar2(255) not null,
    host varchar2(255) not null,
    schema varchar2(255) not null,
    port varchar2(255) not null,
    constraint fk_database_databasetype foreign key (databaseType) references DatabaseType (id),
    constraint pk_database primary key (id)
);

create table Template (
    id number generated by default on null as identity,
    databaseType number not null,
    template clob not null,
    constraint fk_template_databasetype foreign key (databaseType) references DatabaseType (id),
    constraint pk_template primary key (id)
);


create table TargetTable (
    id number generated by default on null as identity,
    database number not null,
    name varchar2(255) not null,
    constraint fk_targettable_database foreign key (database) references Database (id),
    constraint pk_table primary key (id)
);

create table TargetColumn (
    id number generated by default on null as identity,
    targetTable number not null,
    name varchar2(255) not null,
    constraint fk_targetcolumn_targettable foreign key (targetTable) references TargetTable (id),
    constraint pk_column primary key (id)
);

create table Category (
    id number generated by default on null as identity,
    category varchar(255) not null,
    constraint pk_category primary key (id)
);

create table BusinessRuleType (
    id number generated by default on null as identity,
    category NUMBER not null,
    name varchar2(255) not null,
    nameCode varchar2(255) not null,
    explanation varchar2(255),
    example varchar2(255),
    constraintPossible char(1) not null,
    constraint fk_businessruletype_category foreign key (category) references Category (id),
    constraint pk_businessrule_type primary key (id)
);

create table Parameter (
    id number generated by default on null as identity,
    businessRuleType number not null,
    key varchar2(255) not null,
    value varchar2(255) not null,
    constraint fk_parameter_businessruletype foreign key (businessRuleType) references BusinessRuleType (id),
    constraint pk_paramter primary key (id)
);

create table DataType (
    id number generated by default on null as identity,
    type varchar2(255) not null,
    constraint pk_datatype primary key (id)
);

create table DatatypeToParameter (
    parameter number not null,
    dataType number not null,
    constraint pk_datatype_to_parameter primary key (parameter, dataType)
);

create table BusinessRule (
    id number generated by default on null as identity,
    targetColumn number not null,
    template number not null,
    businessRuleType number not null,
    name varchar2(255) not null,
    applied char(1) not null,
    constraint fk_businessrule_template foreign key (template) references Template (id),
    constraint fk_businessrule_targetcolumn foreign key (targetColumn) references TargetColumn (id),
    constraint fk_businessrule_businessruletype foreign key (businessRuleType) references BusinessRuleType (id),
    constraint pk_businessrule primary key (id)
);

create table Binding (
    id number generated by default on null as identity,
    businessRule number not null,
    key varchar2(255) not null,
    value varchar2(255) not null,
    constraint fk_businessrule foreign key (businessRule) references BusinessRule (id),
    constraint pk_binding primary key (id)
);

create table Operator (
    id number generated by default on null as identity,
    businessRule number not null,
    operator varchar(255) not null,
    constraint fk_operator_businessRule foreign key (businessRule) references BusinessRule (id),
    constraint pk_operator primary key (id)
);

create table OperatorOnBusinessRuleType (
    businessRuleType number not null,
    operator number not null,
    constraint fk_businessRuleType_operator foreign key (businessRuleType) references BusinessRuleType (id),
    constraint fk_operator_businessRuleType foreign key (operator) references Operator (id),
    constraint pk_OperatorOnBusinessRuleType primary key (businessRuleType, Operator)
);

