create table BusinessRule (
    id number generated by default on null as identity,
    ruleType varchar2(255) not null,
    description varchar2(255) not null,
    example varchar2(255) not null,
    name varchar2(255) not null,
    errorMessage varchar2(255) not null,
    triggerEvents clob not null,
    constraint ensure_json_br check (triggerEvents is json),
    constraint br_pk primary key (id)
);

create table StrictDataConstraintRule (
    id number generated by default on null as identity,
    constraintPossible number(1) default 0 not null,
    ruleColumn varchar2(255) not null,
    ruleTable varchar2(255) not null,
    rule_id number not null,

    constraint pk_sdcr primary key (id),
    constraint fk_ruleid foreign key (rule_id)
    references BusinessRule (id)
);

create table AttributeRangeRule (
    id number generated by default on null as identity,
    rangeStart number not null,
    rangeEnd number not null,
    inRange number(1) default 0 not null,
    rule_id number not null,
  
    constraint pk_arng primary key (id),
    constraint fk_ruleid_arng foreign key (rule_id)
    references BusinessRule (id)
)
create table AttributeCompareRule (
    id number generated by default on null as identity,
    comparisontype varchar2(255) not null,
    value number not null,
    rule_id number not null,
  
    constraint pk_acmp primary key (id),
    constraint fk_ruleid_acmp foreign key (rule_id)
    references BusinessRule (id)
);

create table AttributeListRule (
    id number generated by default on null as identity,
    list clob not null,
    inList number(1) default 0 not null,
    rule_id number not null,

    constraint ensure_json_alis check (list is json),
    constraint pk_alis primary key (id),
    constraint fk_ruleid_alis foreign key (rule_id)
    references BusinessRule (id)
);
create table AttributeOtherRule (
    id number generated by default on null as identity,
    statement varchar2(255) not null,
    rule_id number not null,
  
    constraint pk_aoth primary key (id),
    constraint fk_ruleid_aoth foreign key (rule_id)
    references BusinessRule (id)
);
create table TupleCompareRule (
    id number generated by default on null as identity,
    otherColumn varchar2(255) not null,
    comparisonType varchar2(255) not null,
    rule_id number not null,
  
    constraint pk_tcmp primary key (id),
    constraint fk_ruleid_tcmp foreign key (rule_id)
    references BusinessRule (id)
);

create table TupleOtherRule (
    id number generated by default on null as identity,
    statement varchar2(255) not null,
    otherColumn varchar2(255) not null,
    rule_id number not null,
    constraint pk_toth primary key (id),
    constraint fk_ruleid_toth foreign key (rule_id)
    references BusinessRule (id)
);
-- todo: make table
create table InterEntityCompareRule (
  id number generated by default on null as identity,
    comparisonType varchar2(255) not null,
    othertable varchar2(255) not null,
    otherColumn varchar2(255) not null,
    rule_id number not null,
  
    constraint pk_icmp primary key (id),
    constraint fk_ruleid_icmp foreign key (rule_id)
    references BusinessRule (id)
);

create table EntityOtherRule (
    id number generated by default on null as identity,
    statement varchar2(255) not null,
    othertable varchar2(255) not null,
    otherColumn varchar2(255) not null,
    rule_id number not null,
  
    constraint pk_eoth primary key (id),
    constraint fk_ruleid_eoth foreign key (rule_id)
    references BusinessRule (id)
);

create table ModifyRule (
    id number generated by default on null as identity,
    code clob not null,
    rule_id number not null,
  
    constraint pk_modi primary key (id),
    constraint fk_ruleid_modi foreign key (rule_id)
    references BusinessRule (id)
)


